export const config = { hearders: { "Content-type": "application/json" } }

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"

export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"

export const USER_IMAGE_UPLOAD_REQUEST = "USER_IMAGE_UPLOAD_REQUEST"

export const USER_IMAGE_UPLOAD_SUCCESS = "USER_IMAGE_UPLOAD_SUCCESS"

export const USER_IMAGE_UPLOAD_FAILED = "USER_IMAGE_UPLOAD_FAILED"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

export const USER_LOGOUT = "USER_LOGOUT"
