export const GET_USER_BY_SEARCH_REQUEST = "GET_USER_BY_SEARCH_REQUEST"

export const GET_USER_BY_SEARCH_SUCCESS = "GET_USER_BY_SEARCH_SUCCESS"

export const GET_USER_BY_SEARCH_FAILS = "GET_USER_BY_SEARCH_FAILS"

export const CLEAR_USER_SEARCH_RESULT = "CLEAR_USER_SEARCH_RESULT"

export const ACCESS_CHAT_BY_ID_REQUEST = "ACCESS_CHAT_BY_ID_REQUEST"

export const ACCESS_CHAT_BY_ID_SUCCESS = "ACCESS_CHAT_BY_ID_SUCCESS"

export const ACCESS_CHAT_BY_ID_FAILED = "ACCESS_CHAT_BY_ID_FAILED"

export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST"

export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS"

export const FETCH_CHAT_FAILD = "FETCH_CHAT_FAILD"

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST"

export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS"

export const CREATE_GROUP_CHAT_FAILED = "CREATE_GROUP_CHAT_FAILED"

export const UPDATE_GROUP_NAME_REQUEST = "UPDATE_GROUP_NAME_REQUEST"

export const UPDATE_GROUP_NAME_SUCCESS = "UPDATE_GROUP_NAME_SUCCESS"

export const UPDATE_GROUP_NAME_FAILED = "UPDATE_GROUP_NAME_FAILED"