export const GET_USER_BY_SEARCH_REQUEST = "GET_USER_BY_SEARCH_REQUEST"

export const GET_USER_BY_SEARCH_SUCCESS = "GET_USER_BY_SEARCH_SUCCESS"

export const GET_USER_BY_SEARCH_FAILS = "GET_USER_BY_SEARCH_FAILS"

export const CLEAR_USER_SEARCH_RESULT = "CLEAR_USER_SEARCH_RESULT"

export const ACCESS_CHAT_BY_ID_REQUEST = "ACCESS_CHAT_BY_ID_REQUEST"

export const ACCESS_CHAT_BY_ID_SUCCESS = "ACCESS_CHAT_BY_ID_SUCCESS"

export const ACCESS_CHAT_BY_ID_FAILED = "ACCESS_CHAT_BY_ID_FAILED"