export const GET_USER_BY_SEARCH_REQUEST = "GET_USER_BY_SEARCH_REQUEST"

export const GET_USER_BY_SEARCH_SUCCESS = "GET_USER_BY_SEARCH_SUCCESS"

export const GET_USER_BY_SEARCH_FAILS = "GET_USER_BY_SEARCH_FAILS"