export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS"

export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED"

export const ADD_NOTIFICATION_SUCCESS = "ADD_NOTIFICATION_SUCCESS"

export const ADD_NOTIFICATION_FAILED = "ADD_NOTIFICATION_FAILED"

export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS"

export const DELETE_NOTIFICATION_FAILED = "DELETE_NOTIFICATION_FAILED"

export const DELETE_ALL_NOTIFICATION_SUCCESS = "DELETE_ALL_NOTIFICATION_SUCCESS"

export const DELETE_ALL_NOTIFICATION_FAILED = "DELETE_ALL_NOTIFICATION_FAILED"